service: finetuning-openai

frameworkVersion: '3'

provider:
  name: aws
  region: eu-central-1

plugins:
  - serverless-offline

functions:
  chatbot:
    image:
      uri: ${env:DOCKER_IMAGE_URI}
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: chat
          method: post
    environment:
      FINE_TUNED_MODEL: ${env:FINE_TUNED_MODEL}
      PINECONE_DATABASE: ${env:PINECONE_DATABASE}
    role: !GetAtt ChatbotLambdaExecutionRole.Arn

resources:
  - ${file(resources/iam-roles.yml)}
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/ssm.yml)}

package:
  individually: true