service: finetuning-openai

frameworkVersion: '3'

provider:
  name: aws
  region: eu-central-1
  #ecr:
    #images:
      #chatbot-lambda:
        #path: ./
        #file: Dockerfile
        #buildArgs:
          #provenance: "false"
          #platform: "linux/amd64"

plugins:
  - serverless-offline

functions:
  chatbot:
    image:
      uri: 445567098565.dkr.ecr.eu-central-1.amazonaws.com/serverless-finetuning-openai-dev@sha256:644c338d0bb910462b4f7eecbf7aa9ca17aa814d9a2c7750c4192952886346a0
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: chat
          method: post
    environment:
      FINE_TUNED_MODEL: ${env:FINE_TUNED_MODEL}
      PINECONE_DATABASE: ${env:PINECONE_DATABASE}
    role: !GetAtt ChatbotLambdaExecutionRole.Arn

resources:
  - ${file(resources/iam-roles.yml)}
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/ssm.yml)}

package:
  individually: true