Resources:
  ChatbotSessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ChatbotSessions
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1